---
title: "Single Cell Analysis"
author: "Roman Reggiardo"
date: "7/10/19"
output: 
  html_notebook:
    highlight: pygments
#output:
#  prettydoc::html_pretty:
#    toc: true
#    highlight: vignette
#    toc_depth: 3
editor_options: 
  chunk_output_type: console
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/home/rreggiar/notebooks')
```

## Figure Code for *insert link here* {.tabset .tabset-fade .tabset-pills}
### On board
```{r echo=FALSE}
# Run this cell to load in all packages used in the notebook
suppressPackageStartupMessages({
library(tidyverse)
#library(ggsci)
#library(ggpubr)
library(ggsignif)
library(ggthemes)
library(ggrepel)
library(ggforce)
library(SingleCellExperiment)
library(tximport)
library(extrafont)
library(Seurat)
library(msigdbr)
#library(GGally)
library(viridis)
#library(ggtern)
library(patchwork)
})


suppressMessages(loadfonts())
```

### Figure themes for publication
```{r echo=FALSE}

theme_set(theme_foundation(base_size = 7, base_family = 'Helvetica') + 
            theme(plot.title = element_blank(),
                panel.background = element_rect(colour = NA),
                plot.background = element_rect(colour = NA),
                panel.border = element_rect(colour = NA),
                axis.title = element_text(face = "bold",size = rel(1)),
                axis.title.y = element_text(angle=90,vjust =2),
                axis.title.x = element_text(vjust = -0.2),
                axis.text = element_text(), 
                axis.line = element_blank(),
                strip.text = element_text(),
                strip.background = element_blank(),
                legend.key.size= unit(0.2, "cm"),
                legend.spacing = unit(0, "cm"),
                legend.key = element_rect(colour = NA),
                legend.title = element_text(face="italic"),
                legend.text = element_text(face = 'bold'),
                plot.margin=margin(10,5,5,5,unit = "mm"),
                panel.grid.major = element_blank(),
                panel.grid.minor = element_blank(),
          ))

set_aale_theme  <- function(){theme_set(theme_foundation(base_size = 7, base_family = 'Helvetica') + 
            theme(plot.title = element_blank(),
                panel.background = element_rect(colour = NA),
                plot.background = element_rect(colour = NA),
                panel.border = element_rect(colour = NA),
                axis.title = element_text(face = "bold",size = rel(1)),
                axis.title.y = element_text(angle=90,vjust =2),
                axis.title.x = element_text(vjust = -0.2),
                axis.text = element_text(), 
                axis.line = element_blank(),
                strip.text = element_text(),
                strip.background = element_blank(),
                legend.key.size= unit(0.2, "cm"),
                legend.spacing = unit(0, "cm"),
                legend.key = element_rect(colour = NA),
                legend.title = element_text(face="italic"),
                legend.text = element_text(face = 'bold'),
                plot.margin=margin(10,5,5,5,unit = "mm"),
                panel.grid.major = element_blank(),
                panel.grid.minor = element_blank()
            ))}
```
### Gene sets of interest
```{r echo=FALSE}
kras.isg.signature <- c("DDX58", "IFIH1", "IFNL1", "IRF9", "IFI27", "OAS2", "IFIT3", "IFIT1", "OASL", "ISG15", "OAS3", "RSAD2", "MX1", "OAS1", "IFI44", "CH25H", "IFIT2", "ISG20", "RNASEL", "IFI6", "HERC5", "HERC6", "GBP3", "GBP1", "IRF1", "ISG15")

liu.isg.signature <- c('ADAR', 'DDX60', 'HERC6', 'IRF7', 'OASL', 'PSM2', 'STAT2', 'TRIM25', 'BST2', 'DHX58', 'IFI35',
                       'ISG15', 'OGFR', 'RSAD2', 'TDRD7', 'UBE2L6', 'CASP1', 'EIF2AK2', 'IFIH1', 'ISG20', 'PARP12',
                       'RTP4', 'TRAFD1', 'USP18', 'CMPK2', 'EPSTI1', 'IFIT2', 'MX1', 'PARP14', 'SAMD9L', 'TRIM14',
                       'CXCL10', 'GBP4', 'IFIT3', 'NMI', 'PNPT1', 'SP110', 'TRIM21')

gs.names = c("KRAS ISG SIGNATURE" , 
             "LIU ISG SIGNATURE" ,
             'HALLMARK IFNA RESPONSE',
             'HALLMARK IFNG RESPONSE',
             'HALLMARK KRAS UP')

rig.i.mda5.induction <- 
  msigdbr(species = 'Homo sapiens') %>% 
  subset(grepl('REACTOME_DDX58', gs_name)) %>% 
  mutate(gs_name = 'RIG_I_MDA5_INDUCTION') %>% 
  select(gene_symbol) %>% 
  unlist() %>% 
  unname()

rig.i.mda5.neg.regulation <- 
  msigdbr(species = 'Homo sapiens') %>% 
  subset(grepl('OF_DDX58', gs_name)) %>% 
  mutate(gs_name = 'RIG_I_MDA5_NEG_REGULATION') %>% 
  select(gene_symbol) %>% 
  unlist() %>% 
  unname()

msig.df.h.ifng <- 
  msigdbr(species = 'Homo sapiens', category = 'H') %>% 
  subset(grepl('_GAMMA_RESPONSE', gs_name)) %>% 
  mutate(gs_name = 'HALLMARK_IFNG_RESPONSE') %>% 
  select(gene_symbol) %>% 
  unlist() %>% 
  unname()

msig.df.h.ifna <- 
  msigdbr(species = 'Homo sapiens', category = 'H') %>% 
  subset(grepl('_ALPHA_RESPONSE', gs_name)) %>% 
  mutate(gs_name = 'HALLMARK_IFNA_RESPONSE') %>% 
  select(gene_symbol) %>% 
  unlist() %>% 
  unname()

kras.signal.up <- 
  msigdbr(species = 'Homo sapiens') %>% 
  filter(gs_name == 'HALLMARK_KRAS_SIGNALING_UP')  %>% 
  select(gene_symbol) %>% 
  unlist() %>% 
  unname()

```

### Suerat and Alevin implementation
```{r}
set.seed(431)

files <- 
  file.path('data/single.cell.rna.seq/output/gencode.te.locus.v.1.index.alevin.out/alevin/quants_mat.gz')
file.exists(files)

txi <- tximport(files, type="alevin")

kras.aale.sc <- CreateSeuratObject(counts = txi$counts, min.cells = 3, 
                                   min.features = 200, project = "KRAS.AALE")

kras.aale.sc[["percent.mt"]] <- PercentageFeatureSet(kras.aale.sc, pattern = "^MT-")
kras.aale.sc[["percent.rp"]] <- PercentageFeatureSet(kras.aale.sc, pattern = '^RP')

VlnPlot(kras.aale.sc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"))
plot1 <- FeatureScatter(kras.aale.sc, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(kras.aale.sc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot3 <- FeatureScatter(kras.aale.sc, feature1 = "nCount_RNA", feature2 = "percent.rp")
CombinePlots(plots = list(plot1, plot2, plot3))

kras.aale.sc <- subset(kras.aale.sc, 
                       subset = nFeature_RNA >= 2000  & 
                         percent.mt < 5 & 
                         nFeature_RNA <= 7000)

kras.aale.sc <- NormalizeData(kras.aale.sc, 
                              normalization.method = "LogNormalize", scale.factor = 10000)

kras.aale.sc <- FindVariableFeatures(kras.aale.sc, selection.method = "vst", nfeatures = 500)

# # Identify the 10 most highly variable genes
# top10 <- head(VariableFeatures(kras.aale.sc), 10)
# top10
# # plot variable features with and without labels
# plot1 <- VariableFeaturePlot(kras.aale.sc)
# plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
# #CombinePlots(plots = list(plot1, plot2))
# plot2

all.genes <- rownames(kras.aale.sc)
kras.aale.sc <- ScaleData(kras.aale.sc, features = all.genes)
kras.aale.sc <- RunPCA(kras.aale.sc, features = VariableFeatures(object = kras.aale.sc))

# Examine and visualize PCA results a few different ways
#print(kras.aale.sc[["pca"]], dims = 1:5, nfeatures = 5)
#VizDimLoadings(kras.aale.sc, dims = 1:5, reduction = "pca")
#DimPlot(kras.aale.sc, reduction = "pca")

#DimHeatmap(kras.aale.sc, dims = 1:4, cells = 10000, balanced = TRUE)

kras.aale.sc <- JackStraw(kras.aale.sc, num.replicate = 100)
kras.aale.sc <- ScoreJackStraw(kras.aale.sc, dims = 1:20)

JackStrawPlot(kras.aale.sc, dims = 1:20)

ElbowPlot(kras.aale.sc)

kras.aale.sc <- FindNeighbors(kras.aale.sc, dims = 1:10)
kras.aale.sc <- FindClusters(kras.aale.sc, resolution = 0.6)

# If you haven't installed UMAP, you can do so via reticulate::py_install(packages ='umap-learn')
kras.aale.sc <- RunUMAP(kras.aale.sc, dims = 1:10)
# note that you can set `label = TRUE` or use the LabelClusters function to help label
# individual clusters
DimPlot(kras.aale.sc, 
        reduction = "umap", 
        pt.size = 2.42,  
        cols = c(viridis(12, option = 'plasma')[1],
                 viridis(12, option = 'inferno')[2],
                 viridis(12, option = 'D')[5],
                 viridis(12, option = 'plasma')[7],
                 viridis(12, option = 'inferno')[9],
                 viridis(12, option = 'D')[11],
                 viridis(12, option = 'magma')[6],
                 viridis(12, option = 'magma')[3])) + 
  set_aale_theme()

#ggsave('../Figures/fig.1/umap.sc.2.5x2.5.pdf', height = 2.5, width = 2.5, units = 'in')

FeaturePlot(kras.aale.sc, features = 'ISG15', pt.size = 2.42) + 
  set_aale_theme()

VlnPlot(kras.aale.sc, features = c("ISG20", "IFI27", "ISG15", 'IRF9', 'IRF3'), ncol = 3)


# DoHeatmap(subset(kras.aale.sc, downsample = 100), 
#           features = c('IRF9','ZNF382', 'IRF3', 'ETV1'), 
#           size = 1, draw.lines = T)
#FeaturePlot(kras.aale.sc, features = cyto.gene.set$V1)
 

kras.aale.sc.markers <- 
  FindAllMarkers(kras.aale.sc, only.pos = F, min.pct = 0.25, logfc.threshold = 0.25) %>% 
  filter(p_val_adj < 0.01)
kras.aale.sc.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)

kras.aale.sc.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC) %>% 
  filter(cluster == 5) %>%
  ungroup() %>% 
  #select(gene) %>% 
  #unlist() -> cluster.5.features
  ggplot(aes(reorder(gene, avg_logFC), avg_logFC)) + 
  geom_col(fill = viridis(12, option = 'D')[11]) + 
  coord_flip() + 
  xlab('') + 
  ylab('avg log2(FoldChange)') + 
  geom_hline(yintercept = seq(0, 3, 0.5), color = 'white', size = rel(0.25))

kras.aale.sc.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC) %>% 
  filter(cluster == 5) %>%
  ungroup() %>% 
  merge(aale.de.seq, by.x = 'gene', by.y = 'Gene') %>% 
  ggplot(aes(avg_logFC, log2fc)) + 
  geom_point()
  
ggsave('../Figures/fig.1/clust.5.bar.2.5x1.5.pdf', height = 2.5, width = 1.5, units = 'in')


kras.aale.sc.markers.heatmap <- 
  kras.aale.sc.markers %>% 
  group_by(cluster) %>% 
  top_n(n = 5, wt = (sin(avg_logFC) * -log10(p_val + 0.0000001)))

kras.aale.sc.markers.heatmap <- 
  kras.aale.sc.markers %>% 
  group_by(cluster) %>% 
  top_n(n = 5, wt = -p_val) 
```

### Plotting normalized counts
```{r}
# extract scaled, normalized counts
kras.aale.sc.norm.counts <- as.data.frame(as.matrix(kras.aale.sc[["RNA"]]@scale.data))
# extract barcodes
kras.barcode.counts <- 
  as.data.frame(as.matrix(kras.aale.sc@active.ident)) %>% 
  rownames_to_column('barcode')
# rename column to reflect data
names(kras.barcode.counts)[2] <- 'cluster'
# tidy 
kras.aale.sc.norm.counts <- 
  kras.aale.sc.norm.counts %>% 
  rownames_to_column('gene') %>% 
  gather(barcode, norm.counts, -gene) 
# pair barcodes and counts
kras.aale.sc.norm.counts <- 
  merge(kras.aale.sc.norm.counts, kras.barcode.counts, by = 'barcode')
# make TE class gene sets
alu.gene.set <- subset(kras.aale.sc.norm.counts, grepl('^Alu', gene))$gene
fram.gene.set <- subset(kras.aale.sc.norm.counts, grepl('FRAM', gene))$gene
mer.gene.set <- subset(kras.aale.sc.norm.counts, grepl('^MER', gene))$gene
herv.gene.set <- subset(kras.aale.sc.norm.counts, grepl('^HERV', gene))$gene
ltr.gene.set <- subset(kras.aale.sc.norm.counts, grepl('^LTR', gene))$gene
line.gene.set <- subset(kras.aale.sc.norm.counts, grepl('^L1', gene))$gene
cd47.gene.set <- subset(kras.aale.sc.norm.counts, gene == 'CD47')$gene
# make znf gene set
znfs.gene.set <- c('ZFP92', 'ZNF135', 'ZNF334', 'ZNF34', 'ZNF347', 'ZNF345A', 'ZNF345C',
                     'ZNF382', 'ZNF415', 'ZNF433', 'ZNF441', 'ZNF442', 'ZNF471', 'ZNF506',
                     'ZNF528', 'ZNF558', 'ZNF563', 'ZNF568', 'ZNF582', 'ZNF586', 'ZNF605',
                     'ZNF655', 'ZNF662', 'ZNF667', 'ZNF682', 'ZNF736', 'ZNF788', 'ZNF793',
                     'ZNF814', 'ZNF83', 'ZNF880', 'ZNF90', 'ZNF10', 'ZNF133', 'ZNF665', 'ZNF699',
                     'ZNF792')
gene.set.list <- c(alu.gene.set,
                   mer.gene.set,
                   herv.gene.set,
                   ltr.gene.set,
                   line.gene.set,
                   fram.gene.set,
                   znfs.gene.set,
                   cd47.gene.set,
                   ISG.GS$gene_symbol, 
                   ISG.RS$gene_symbol,
                   DER.IFN.ALPHA.UP$gene_symbol,
                   DER.IFN.BETA.UP$gene_symbol,
                   DER.IFN.GAMMA.UP$gene_symbol,
                   RIG.I.MDA.5.INDUCTION$gene_symbol)

# spread data into gene columns
norm.counts.plot <- 
  kras.aale.sc.norm.counts %>% 
  group_by(barcode) %>% 
  subset(gene %in% gene.set.list) %>%
  spread(gene, norm.counts)

norm.counts.present.alu.gene.set <- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% c(alu.gene.set)) 

norm.counts.present.fram.gene.set <- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% fram.gene.set)

norm.counts.present.mer.gene.set <- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% c(mer.gene.set)) 

norm.counts.present.herv.gene.set <- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% c(herv.gene.set)) 

norm.counts.present.ltr.gene.set <- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% c(ltr.gene.set)) 

norm.counts.present.line.gene.set <- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% c(line.gene.set)) 

norm.counts.present.znfs.gene.set <- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% c(znfs.gene.set)) 

norm.counts.present.cd47.gene.set <- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% c(cd47.gene.set)) 

norm.counts.present.ISG.GS <- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% c(ISG.GS$gene_symbol)) 

norm.counts.present.ISG.RS <- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% c(ISG.RS$gene_symbol))

norm.counts.present.DER.IFN.ALPHA.UP <- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% c(DER.IFN.ALPHA.UP$gene_symbol)) 

norm.counts.present.DER.IFN.BETA.UP <- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% c(DER.IFN.BETA.UP$gene_symbol)) 

norm.counts.present.DER.IFN.GAMMA.UP<- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% c(DER.IFN.GAMMA.UP$gene_symbol)) 

norm.counts.present.RIG.I.MDA.5.INDUCTION <- 
  colnames(norm.counts.plot) %>% 
  subset(. %in% c(RIG.I.MDA.5.INDUCTION$gene_symbol)) 


norm.counts.plot$TE.AVG <- 
  rowMeans(norm.counts.plot[, c(norm.counts.present.alu.gene.set,
                            norm.counts.present.mer.gene.set,
                            norm.counts.present.herv.gene.set, 
                            norm.counts.present.ltr.gene.set, 
                            norm.counts.present.line.gene.set,
                            norm.counts.present.fram.gene.set)])
norm.counts.plot$ALU <- 
  rowMeans(norm.counts.plot[, norm.counts.present.alu.gene.set])
norm.counts.plot$MER <- 
  rowMeans(norm.counts.plot[, norm.counts.present.mer.gene.set])
norm.counts.plot$HERV <- 
  rowMeans(norm.counts.plot[, norm.counts.present.herv.gene.set])
norm.counts.plot$LTR <- 
  rowMeans(norm.counts.plot[, norm.counts.present.ltr.gene.set])
norm.counts.plot$LINE <- 
  rowMeans(norm.counts.plot[, norm.counts.present.line.gene.set])
norm.counts.plot$ZNF <- 
  rowMeans(norm.counts.plot[, norm.counts.present.znfs.gene.set])
norm.counts.plot$CD47 <- 
  rowMeans(norm.counts.plot[, norm.counts.present.cd47.gene.set])
norm.counts.plot$ISG.GS <- 
  rowMeans(norm.counts.plot[, norm.counts.present.ISG.GS])
norm.counts.plot$ISG.RS <- 
  rowMeans(norm.counts.plot[, norm.counts.present.ISG.RS])
norm.counts.plot$DER.IFN.ALPHA.UP <- 
  rowMeans(norm.counts.plot[, norm.counts.present.DER.IFN.ALPHA.UP])
norm.counts.plot$DER.IFN.BETA.UP <- 
  rowMeans(norm.counts.plot[, norm.counts.present.DER.IFN.BETA.UP])
norm.counts.plot$DER.IFN.GAMMA.UP <- 
  rowMeans(norm.counts.plot[, norm.counts.present.DER.IFN.GAMMA.UP])
norm.counts.plot$RIG.I.MDA.5.INDUCTION <- 
  rowMeans(norm.counts.plot[, norm.counts.present.RIG.I.MDA.5.INDUCTION])
norm.counts.plot$FRAM  <- 
  rowMeans(norm.counts.plot[, norm.counts.present.fram.gene.set])

norm.counts.plot.final <- 
  norm.counts.plot %>% 
  select(barcode, cluster, ALU, MER, HERV, LTR, LINE, TE.AVG, ISG.GS, ISG.RS, ZNF,
         CD47, DER.IFN.ALPHA.UP, DER.IFN.BETA.UP, DER.IFN.GAMMA.UP, 
         RIG.I.MDA.5.INDUCTION)

norm.counts.p.mat <- 
  cor_pmat(subset(norm.counts.plot.final, cluster == 2)[,-c(1,2)])

gene.set.cor.df <- 
  cor(subset(norm.counts.plot.final)[,-c(1,2)])

ggcorrplot::ggcorrplot(gene.set.cor.df, lab = T)


cluster.id.color.lookup <- tibble(cluster = c(0,1,2,3,4,5),
                                  color = c('#440154FF',
                 '#404788FF',
                 '#2D708EFF',
                 '#20A387FF',
                 '#73D055FF',
                 '#FDE725FF'))

```

```{r}
make.gene.set.cor.plot <- function(cluster.choice, x.val , y.val){

  gene.set.cor.df <- 
  cor(subset(norm.counts.plot.final, cluster == cluster.choice)[,-c(1,2)])
  gene.set.cor.small <- 
  gene.set.cor.df[! colnames(gene.set.cor.df) %in% c('ALU', 'FRAM', 
                                                   'MER', 'HERV', 
                                                   'LTR', 'LINE', 'TE.AVG', 'ZNF', 'CD47'),
                  ! rownames(gene.set.cor.df) %in% c('ISG.GS', 'ISG.RS', 
                                                   'DER.IFN.ALPHA.UP', 'DER.IFN.BETA.UP', 
                                                   'DER.IFN.GAMMA.UP', 'RIG.I.MDA.5.INDUCTION')]

  tidy.gene.set.cor.small <- 
    gene.set.cor.small %>% 
    as.data.frame() %>% 
    rownames_to_column('compare') %>% 
    gather(te.set, pearson, -compare) %>% 
    ggplot(aes(compare, te.set, 
               fill = pearson,
               label = round(pearson, 2))) + 
    geom_tile() + 
    geom_text(size = 2, color = 'white', alpha = 1) +
    scale_alpha_continuous(guide = F, breaks = c(-0.25, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8)) + 
    scale_fill_viridis_c(limits = c(-0.25, 0.75), direction = -1) + 
    xlab('') + ylab('') + 
    theme(axis.text.x = element_text(angle = 40, hjust = 1)) + 
    scale_y_discrete(limits = c('MER', 'LINE', 'LTR', 'HERV', 'ALU', 'TE.AVG', 'ZNF', 'CD47')) + 
    scale_x_discrete(limits = c('ISG.GS',
                                'ISG.RS',
                                'DER.IFN.ALPHA.UP',
                                'DER.IFN.BETA.UP',
                                'DER.IFN.GAMMA.UP',
                                'RIG.I.MDA.5.INDUCTION'))
  
  cluster.id.color <- cluster.id.color.lookup$color[cluster.id.color.lookup$cluster == cluster.choice]
  
  scatter.plot <- 
    ggplot(subset(norm.counts.plot.final, ALU > -3 & cluster == cluster.choice), 
       aes_string(x = x.val, 
                  y = y.val)) + 
  geom_point(alpha = 0.4,
       color = cluster.id.color) + 
  geom_rug( color = cluster.id.color) 
  
  list(cluster.id.color.lookup$color[cluster.id.color.lookup$cluster == cluster.choice], tidy.gene.set.cor.small, scatter.plot)
}

make.gene.set.cor.plot(2, x.val = 'CD47', y.val = 'RIG.I.MDA.5.INDUCTION')

```

Specific AluSx1:
```{r}
ggplot(subset(norm.counts.plot, ALU > -3), 
       aes(x = AluSx1, 
                  y = ALU)) + 
  geom_point(alpha = 0.4) + 
  geom_rug() + 
  geom_smooth(method = 'lm', color = 'grey')

summary(lm(AluSx1 ~ ALU, norm.counts.plot))

norm.counts.plot.final <- 
  norm.counts.plot %>% 
  select(barcode, cluster, ALU, MER, HERV, LTR, LINE, ZNF, TE.AVG, ISG.GS, ISG.RS,
         DER.IFN.ALPHA.UP, DER.IFN.BETA.UP, DER.IFN.GAMMA.UP, 
         RIG.I.MDA.5.INDUCTION, AluSx1)

find.cluster.corr <- function(cluster.choice){
  gene.set.cor.df <- 
  cor(subset(norm.counts.plot.final, cluster == cluster.choice)[,-c(1,2)])
  
  gene.set.cor.small <- 
  gene.set.cor.df[! colnames(gene.set.cor.df) %in% c('ALU', 'FRAM', 
                                                   'MER', 'HERV', 
                                                   'LTR', 'LINE', 'TE.AVG'),
                  ! rownames(gene.set.cor.df) %in% c('ISG.GS', 'ISG.RS', 
                                                   'DER.IFN.ALPHA.UP', 'DER.IFN.BETA.UP', 
                                                   'DER.IFN.GAMMA.UP', 'RIG.I.MDA.5.INDUCTION','ALU', 'FRAM', 
                                                   'MER', 'HERV', 
                                                   'LTR', 'LINE', 'TE.AVG', 'ZNF')]
 
  gene.set.cor.small <- as.data.frame(gene.set.cor.small)
  names(gene.set.cor.small) <- cluster.choice
  return(gene.set.cor.small)
}

alusx1.0 <- find.cluster.corr(0)
alusx1.1 <- find.cluster.corr(1)
alusx1.2 <- find.cluster.corr(2)
alusx1.3 <- find.cluster.corr(3)
alusx1.4 <- find.cluster.corr(4)
alusx1.5 <- find.cluster.corr(5)

alusx.cor.cluster <- 
  cbind(alusx1.0,alusx1.1,alusx1.2,alusx1.3,alusx1.4,alusx1.5) %>% 
    rownames_to_column('compare') %>% 
    gather(te.set, pearson, -compare) %>% 
    filter(compare != 'AluSx1') %>% 
    ggplot(aes(compare, te.set, 
               fill = pearson,
               label = round(pearson, 2))) + 
    geom_tile() + 
    geom_text(size = 2, color = 'white', alpha = 1) +
    scale_alpha_continuous(guide = F, breaks = c(-0.25, 0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.8)) + 
    scale_fill_viridis_c(limits = c(-0.25, 0.75), direction = -1) + 
    xlab('') + ylab('Cluster') + 
    theme(axis.text.x = element_text(angle = 40, hjust = 1)) + 
    scale_x_discrete(limits = c('ISG.GS',
                                'ISG.RS',
                                'DER.IFN.ALPHA.UP',
                                'DER.IFN.BETA.UP',
                                'DER.IFN.GAMMA.UP',
                                'RIG.I.MDA.5.INDUCTION',
                                'ZNF'))

alusx.cor.cluster
```


### Plotting normalized abundance of 'metagenes'
```{r}
gene.set.kras.aale.sc <- kras.aale.sc  

add.gene.set.to.sc <- function(gene.set, name){
  gene.set <- 
    rownames(gene.set.kras.aale.sc[['RNA']]@data)[rownames(gene.set.kras.aale.sc[['RNA']]@data) %in% gene.set]
  
  # Get mean expression of genes of interest per cell
  mean.exp <- 
    colMeans(x = gene.set.kras.aale.sc[['RNA']]@data[rownames(gene.set.kras.aale.sc[['RNA']]@scale.data) %in% gene.set,], na.rm = TRUE)
  
  # Add mean expression values in 'object@meta.data$gene.set.score'
  name <- deparse(substitute(name))
  gene.set.kras.aale.sc@meta.data[, `name`] <- mean.exp 
  return(gene.set.kras.aale.sc)
}

gene.set.kras.aale.sc <- add.gene.set.to.sc(liu.isg.signature, `liu.isg.signature`)
gene.set.kras.aale.sc <- add.gene.set.to.sc(kras.isg.signature, `kras.isg.signature`)
gene.set.kras.aale.sc <- add.gene.set.to.sc(msig.df.h.ifna, `msig.df.h.ifna`)
gene.set.kras.aale.sc <- add.gene.set.to.sc(msig.df.h.ifng, `msig.df.h.ifng`)
gene.set.kras.aale.sc <- add.gene.set.to.sc(kras.signal.up, `kras.signal.up`)
gene.set.kras.aale.sc <- add.gene.set.to.sc(rig.i.mda5.induction, `rig.i.mda5.induction`)
gene.set.kras.aale.sc <- add.gene.set.to.sc(rig.i.mda5.neg.regulation, `rig.i.mda5.neg.regulation`)

vln_theme <- function() {theme_set(theme_foundation(base_size = 7, base_family = 'Helvetica') + 
            theme(plot.title = element_blank(),
                panel.background = element_rect(colour = NA),
                plot.background = element_rect(colour = NA),
                panel.border = element_rect(colour = NA),
                axis.title = element_text(face = "bold",size = rel(1)),
                axis.title.y = element_text(angle=90,vjust =2),
                axis.title.x = element_blank(),
                axis.text = element_text(), 
                axis.line = element_blank(),
                strip.text = element_text(),
                strip.background = element_blank(),
                legend.key.size= unit(0.2, "cm"),
                legend.spacing = unit(0, "cm"),
                legend.title = element_text(face="italic"),
                legend.text = element_text(face = 'bold'),
                plot.margin=margin(10,5,5,5,unit = "mm"),
                panel.grid.major = element_blank(),
                panel.grid.minor = element_blank(),
                legend.position = 'NA'
          ))
}

make.gene.set.vln <- function(name){
  
  name <- deparse(substitute(name))

  return(VlnPlot(gene.set.kras.aale.sc, 
        features = `name`, 
        nrow = 1, pt.size = 0, size = 0.5, 
        cols = c(viridis(12, option = 'plasma')[1],
                 viridis(12, option = 'inferno')[2],
                 viridis(12, option = 'D')[5],
                 viridis(12, option = 'plasma')[7],
                 viridis(12, option = 'inferno')[9],
                 viridis(12, option = 'D')[11])) + 
  xlab('') + 
    vln_theme() + 
    theme(plot.margin = unit(c(0, 0, 0, 0), "cm")))

}

liu.isg.vln <- make.gene.set.vln(`liu.isg.signature`)
kras.isg.vln <- make.gene.set.vln(`kras.isg.signature`)
msig.df.h.ifna.vln <- make.gene.set.vln(`msig.df.h.ifna`)
msig.df.h.ifng.vln <- make.gene.set.vln(`msig.df.h.ifng`)
kras.signal.up.vln <- make.gene.set.vln(`kras.signal.up`)
rig.i.mda5.induction.vln <- make.gene.set.vln(`rig.i.mda5.induction`)
rig.i.mda5.neg.regulation.vln <- make.gene.set.vln(`rig.i.mda5.neg.regulation`)

patchwork::wrap_plots(list(liu.isg.vln, kras.isg.vln))

rig.i.mda5.induction.vln
  
rig.i.mda5.neg.regulation.vln


ggsave('../Figures/fig.1/stacked.vln.3x4.pdf', height = 3, width = 4, units = 'in')


ddx58.vln <- VlnPlot(gene.set.kras.aale.sc, 
        features = c('DDX58'), 
        nrow = 1,pt.size = 0, size = 0.5, 
        cols = c(viridis(12, option = 'plasma')[1],
                 viridis(12, option = 'inferno')[2],
                 viridis(12, option = 'D')[5],
                 viridis(12, option = 'plasma')[7],
                 viridis(12, option = 'inferno')[9],
                 viridis(12, option = 'D')[11])) + 
  xlab('') + set_aale_theme()

ifih1.vln <- VlnPlot(gene.set.kras.aale.sc, 
        features = c('AluY'), 
        nrow = 1,pt.size = 0, size = 0.5, 
        cols = c(viridis(12, option = 'plasma')[1],
                 viridis(12, option = 'inferno')[2],
                 viridis(12, option = 'D')[5],
                 viridis(12, option = 'plasma')[7],
                 viridis(12, option = 'inferno')[9],
                 viridis(12, option = 'D')[11])) + 
  xlab('') + set_aale_theme()

patchwork::wrap_plots(list(ddx58.vln, ifih1.vln), ncol = 2, guides = 'collect')

ggsave('../Figures/fig.1/dsRNA.sc.vln.3x4.pdf', height = 2.5, width = 3.5, units = 'in')

test.mtx <- as.matrix(mean.exp)
colnames(test.mtx) <- 'DER.IFN.GAMMA.UP'



t(test.mtx)

gene.set.kras.aale.sc@assays$DER.IFN.GAMMA.UP <- CreateAssayObject(t(test.mtx))

as_tibble(as.matrix(gene.set.kras.aale.sc@assays$DER.IFN.GAMMA.UP))

as_tibble(as.matrix(gene.set.kras.aale.sc@meta.data$seurat_clusters))
gene.set.kras.aale.sc@meta.data$RIG.I.MDA.5.INDUCTION

DoHeatmap(subset(gene.set.kras.aale.sc, downsample = 100), 
          assay = 'cluster.5.features', 
          size = 3) +
  theme_classic() + 
            theme(panel.background = element_rect(fill = 'white'),
                axis.text = element_text(family = 'Helvetica', size = 6),
                axis.title = element_text(family = 'Helvetica', size = 6),
                legend.text = element_text(family = 'Helvetica', size = 6),
                legend.title = element_text(family = 'Helvetica', size = 6),
                axis.line = element_blank(),
                strip.text = element_text(family = 'Helvetica', size = 8, face = 'bold'),
                strip.background = element_blank(),
                axis.text.x = element_text(angle = 40, hjust = 1))

FeaturePlot(gene.set.kras.aale.sc, 
            features = c('msig.df.h.ifng'), 
            pt.size = .42, sort.cell = T,
            cols = c(viridis(2, direction = -1))) + set_aale_theme()

ggsave('../Figures/fig.1/hifng.sc.2.5x2.pdf', height = 2.5, width = 2, units = 'in')
```

#### RIG-I vs. MDA5
```{r}
kras.aale.sc.norm.counts.receptor.scatter <- 
  kras.aale.sc.norm.counts %>% 
  filter(gene %in% c('IFIH1','DDX58')) %>% 
  spread(gene, norm.counts) %>% 
  ggplot(aes(IFIH1, DDX58, color = cluster)) + 
  geom_point() + 
  facet_wrap(~cluster)
kras.aale.sc.norm.counts.receptor.scatter
```

```{r}
## https://github.com/satijalab/seurat/issues/528 ##

make.msig.df <- function(in.df){
  msig.df <- 
    in.df %>% 
    select(gene_symbol, gs_name) %>% 
    merge(lookup,
        by.x = 'gs_name',
        by.y = 'gs.name') %>% 
  split(x = .$gene_symbol, f = .$re.name)
  return(msig.df) 
}

ISG.GS <- make.msig.df(ISG.GS)
ISG.RS <- make.msig.df(ISG.RS)
DER.IFN.GAMMA.UP <- make.msig.df(DER.IFN.GAMMA.UP)
DER.IFN.ALPHA.UP <- make.msig.df(DER.IFN.ALPHA.UP)
DER.IFN.BETA.UP <- make.msig.df(DER.IFN.BETA.UP)
RIG.I.MDA.5.INDUCTION <- make.msig.df(RIG.I.MDA.5.INDUCTION)
KRAS.SIGNALING.UP <- make.msig.df(KRAS.SIGNALING.UP)

gene.set.feature.plot <- function(gene.set.vector){
  
  gene.set.kras.aale.sc <- kras.aale.sc  
  
  gene.set <- 
      rownames(gene.set.kras.aale.sc[['RNA']]@data)[rownames(gene.set.kras.aale.sc[['RNA']]@data) %in% KRAS.SIGNALING.UP$gene_symbol]
  
  # Get mean expression of genes of interest per cell
  mean.exp <- 
      colMeans(x = gene.set.kras.aale.sc[['RNA']]@data[rownames(gene.set.kras.aale.sc[['RNA']]@scale.data) %in% gene.set.vector,], na.rm = TRUE)
    
  # Add mean expression values in 'object@meta.data$gene.set.score'
    if (all(names(x = mean.exp) == rownames(x = gene.set.kras.aale.sc@meta.data))) {
    cat("Cell names order match in 'mean.exp' and 'gene.set.kras.aale.sc@meta.data':\n", 
      "adding gene set mean expression values in 'gene.set.kras.aale.sc@meta.data$gene.set.score'")
    gene.set.kras.aale.sc@meta.data$gene.set.vector <- mean.exp
    }

  # Plot mean expression using Seurat::FeaturePlot()
  FeaturePlot(object = gene.set.kras.aale.sc, 
            features = as.character(gene.set.vector), 
            cols = c('yellow', 'blue'),
            pt.size = 4, 
            reduction = 'umap') +
    theme_classic() + 
            theme(panel.background = element_rect(fill = 'white'),
                axis.text = element_text(family = 'Helvetica', size = 6),
                axis.title = element_text(family = 'Helvetica', size = 6),
                legend.text = element_text(family = 'Helvetica', size = 6),
                legend.title = element_text(family = 'Helvetica', size = 6),
                axis.line = element_blank(),
                strip.text = element_text(family = 'Helvetica', size = 8, face = 'bold'),
                strip.background = element_blank())
}

# Plot mean expression using Seurat::FeaturePlot()
FeaturePlot(object = gene.set.kras.aale.sc, 
          features = 'RIG.I.MDA.5.INDUCTION', 
          cols = c('grey',viridis(12, option = 'D')[7] ),
          pt.size = 2, 
          reduction = 'umap') +
  theme_classic() + 
          theme(panel.background = element_rect(fill = 'white'),
              axis.text = element_text(family = 'Helvetica', size = 6),
              axis.title = element_text(family = 'Helvetica', size = 6),
              legend.text = element_text(family = 'Helvetica', size = 6),
              legend.title = element_text(family = 'Helvetica', size = 6),
              axis.line = element_blank(),
              strip.text = element_text(family = 'Helvetica', size = 8, face = 'bold'),
              strip.background = element_blank())
```

### Export *Seurat* object to loom for import into scanpy:
```{r}
library(scater)
library(loomR)

kras.aale.sc@graphs <- list()

kras.aale.sc.loom <- as.loom(kras.aale.sc,
                             filename = '../data/kras.aale.sc.te.loom',
                             verbose = F)

kras.aale.sc.loom
kras.aale.sc.loom$close_all()
```

### Monocle V.2:
```{r}
library(monocle)
monocle.kras.aale.sc <- importCDS(kras.aale.sc, import_all = TRUE)

```

